common/urls.py
"""
created at: 2023-03-04
"""
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from stocktracker import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stocktracker/', include('stocktracker.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),
]

stocktracker/urls.py
"""
created at: 2023-03-04
"""
from django.urls import path

from . import views

app_name = 'stocktracker'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:user_id>/', views.index),
    path('account/create/', views.account_create, name='account_create'),
    path('cash/update/', views.asset_cash_update, name='asset_cash_update'),
]

common/models.py
from django.db import models

# Create your models here.

stocktracker/models.py
"""
created at: 2023-03-04
"""
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Account(models.Model):
    """
    table for account
    """
    # id
    created_at = models.DateTimeField()
    name = models.CharField(max_length=50)
    name_bank = models.CharField(max_length=20)
    balance = models.IntegerField()
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)

class AccountHistory(models.Model):
    """
    transection history of Account table
    """
    # id
    created_at = models.DateTimeField()
    # from_account = models.ForeignKey(Account, on_delete=models.PROTECT)
    # to_account = models.ForeignKey(Account, on_delete=models.PROTECT)
    from_account = models.FloatField()
    to_account = models.FloatField()
    amount  = models.IntegerField()

class AssetCash(models.Model):
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    balance = models.IntegerField()
    account_id = models.ForeignKey(Account, on_delete=models.CASCADE)

class AssetStock(models.Model):
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    account_id = models.ForeignKey(Account, on_delete=models.CASCADE)
    stock_code = models.CharField(max_length=6)
    stock_amount = models.IntegerField()
    balance = models.IntegerField()

common/forms.py
"""
created at: 2023-03-04
"""

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    """
    user
    """
    email = forms.EmailField(label="이메일")

    class Meta:
        """
        form for sign up
        """
        model = User
        fields = ("username", "password1", "password2", "email")

stocktracker/forms.py
from django import forms
from stocktracker.models import Account, AssetCash, AssetStock

class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['name', 'name_bank']
        labels = {
            'name': '계좌 이름',
            'name_bank': '증권사 이름',
        }

class AssetCashForm(forms.ModelForm):
    class Meta:
        model = AssetCash
        fields = ['account_id', 'balance']
        labels = {
            'account_id': '계좌 이름',
            'balance': '잔고',
        }

common/views.py
"""
created at: 2023-03-04
"""

from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm

def signup(request):
    """
    post request
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('stocktracker:index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

stocktracker/views.py
"""
created at: 2023-03-04
"""

from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Account, AssetCash, AssetStock
from .forms import AccountForm, AssetCashForm
from django.contrib.auth.decorators import login_required

# Create your views here.

# def home(request):
#     """
#     home
#     """
#     account_list = Account.objects.order_by('-balance')
#     context = {'account_list':account_list}
#     return render(request, "stocktracker/index.html", context)

def index(request):
    """
    Index
    """
    if request.user.is_authenticated:
        account_list =  Account.objects.filter(user_id=request.user).order_by('-balance')
    else:
        account_list = None
    context = {'account_list':account_list}
    return render(request, 'stocktracker/index.html', context)

@login_required(login_url='common:login')
def account_create(request):
    """
    create account
    """
    if request.method == 'POST':
        form = AccountForm(request.POST)
        if form.is_valid():
            account = form.save(commit=False)
            account.user_id = request.user
            account.created_at = timezone.now()
            account.balance = 0
            account.save()
            # create asset_cash
            asset_cash = AssetCash(
                account_id=account,
                created_at = timezone.now(),
                updated_at = timezone.now(),
                user_id = request.user,
                balance=0
            )
            asset_cash.save()
            return redirect("stocktracker:asset_cash_update")
    else:
        form = AccountForm(initial={'balance':0})
    return render(request, 'stocktracker/account_form.html', {'form':form})

@login_required(login_url='common:login')
def asset_cash_update(request):
    """
    update asset_cash
    """
    account_list =  Account.objects.filter(user_id=request.user)
    if request.method == 'POST':
        form = AssetCashForm(request.POST)
        if form.is_valid():
            account = Account.objects.get(id=int(request.POST['account_id']))
            account.balance += int(request.POST['balance'])
            account.save()
            asset_cash = AssetCash.objects.get(account_id=int(request.POST['account_id']))
            asset_cash.updated_at = timezone.now()
            asset_cash.balance = int(request.POST['balance'])
            asset_cash.save()
            return redirect("stocktracker:index")
    else:
        form = AssetCash()
    return render(request, 'stocktracker/asset_cash_form.html', {'form':form, 'account_list':account_list})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Custom styles for this template-->
    <link href="{% static 'css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- stocktracker CSS -->
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"> -->
    <title>Stock Tracker</title>
</head>

<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        {% include "stocktracker/sidebar.html" %}

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-fles felx-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                {% include "stocktracker/topbar.html" %}
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>
</body>

</html>

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Login</h1>
</div>
<div class="row">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 ID</label>
            <input type="text" class="form-control" name="username" id="username"
                value="{{ form.username.value | default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="text" class="form-control" name="password" id="password"
                value="{{ form.password.value | default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">login</button>
        <a href="{% url 'common:signup' %}" class="btn btn-outline-dark" role="button" data-bs-toggle="button">Sign
            Up</a>
    </form>
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/stocktracker/account_form.html
{% extends "base.html" %}
{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Create Account</h1>
</div>
<div class="card shadow mb-4">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Account Info</h6>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <!-- start displaying error section-->
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                {% if field.errors %}
                <div>
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                </div>
                {% endif %}
                {% endfor %}
            </div>
            {% endif %}
            <!-- end error section -->
            <div class="mb-3">
                <label for="name" class="form-label">계좌 이름</label>
                <input type="text" class="form-control" name="name" id="name"
                    value="{{ form.name.value | default_if_none:''}}">
            </div>
            <div class="mb-3">
                <label for="name_bank" class="form-label">증권사 이름</label>
                <input type="text" class="form-control" name="name_bank" id="name_bank"
                    value="{{ form.name_bank.value | default_if_none:''}}">
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
            <a href="{% url 'stocktracker:index' %}" class="btn btn-secondary" role="button" data-bs-toggle="button"
                style="margin-left: 1rem;">Cancel</a>
        </form>
    </div>
</div>
{% endblock %}

templates/stocktracker/account_list.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
<a href="{% url 'common:logout' %}">{{user.username}} (로그아웃)</a>
{% else %}
<a href="{% url 'common:login' %}">로그인</a>
<a href="{% url 'common:signup' %}">회원가입</a>
{% endif %}
{% endblock %}

templates/stocktracker/asset_cash_form.html
{% extends "base.html" %}
{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">update Cash</h1>
</div>
<div class="card shadow mb-4">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Cash Info</h6>
    </div>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <!-- start displaying error section-->
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                {% if field.errors %}
                <div>
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                </div>
                {% endif %}
                {% endfor %}
            </div>
            {% endif %}
            <!-- end error section -->
            <div class="mb-3">
                <label for="name" class="form-label">계좌 이름</label>
                <select type="text" class="form-select" name="account_id" id="account_id">
                    {% for account in account_list %}
                    <option value="{{ account.id }}">{{ account.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
                <label for="balance" class="form-label">잔고</label>
                <input type="text" class="form-control" name="balance" id="balance" onkeyup="inputNumberFormat(this)"
                    value="{{ form.balance.value | default_if_none:''}}">
            </div>
            <button onclick="submitNumber(form)" type="submit" class="btn btn-primary">Save</button>
            <a href="{% url 'stocktracker:index' %}" class="btn btn-secondary" role="button" data-bs-toggle="button"
                style="margin-left: 1rem;">Cancel</a>
        </form>
    </div>
</div>
{% include "stocktracker/number_comma.html" %}
{% endblock %}

templates/stocktracker/index.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
{% else %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Please login</h1>
</div>
{% endif %}
{% endblock %}

templates/stocktracker/number_comma.html
<script type="text/javascript">
    function comma(str) {
        str = String(str);
        return str.replace(/(\d)(?=(?:\d{3})+(?!\d))/g, '$1,');
    }

    function uncomma(str) {
        str = String(str);
        return str.replace(/[^\d]+/g, '');
    }

    function inputNumberFormat(obj) {
        obj.value = comma(uncomma(obj.value));
    }

    function inputOnlyNumberFormat(obj) {
        obj.value = onlynumber(uncomma(obj.value));
    }

    function onlynumber(str) {
        str = String(str);
        return str.replace(/(\d)(?=(?:\d{3})+(?!\d))/g, '$1');
    }

    function submitNumber(obj) {
        obj.balance.value = uncomma(obj.balance.value);
    }
</script>

templates/stocktracker/sidebar.html
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'stocktracker:index' %}">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3"> stocktracker </div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'stocktracker:index' %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Settings
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true"
            aria-controls="collapseTwo">
            <i class="fas fa-fw fa-cog"></i>
            <span>Accounts</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Account list:</h6>
                <a class="collapse-item" href="{% url 'stocktracker:account_create' %}">+ Add Account</a>
                <hr style="margin: 0.3rem; color:rgba(0,0,0, .20); margin-inline-start: 1rem; margin-inline-end: 1rem;">
                <a class="collapse-item" href="{% url 'stocktracker:asset_cash_update' %}">update Cash</a>
                <a class="collapse-item" href="#">update Stock</a>
            </div>
        </div>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="tables.html">
            <i class="fas fa-fw fa-table"></i>
            <span>Planning</span></a>
    </li>
    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>
<!-- End of Sidebar -->

templates/stocktracker/topbar.html
{% load static %}
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>


    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            {% if user.is_authenticated %}
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.username }}</span>
                <img class="img-profile rounded-circle" src="{% static 'img/undraw_profile.svg' %}">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    {{ user.username }}
                </a>
                <a class="dropdown-item" href="{% url 'common:logout' %}">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
            {% else %}
            <a href="{% url 'common:login' %}" class="btn btn-outline-dark" role="button"
                data-bs-toggle="button">login</a>
            {% endif %}
        </li>

    </ul>

</nav>